// Ticker universes. Curated snapshots — symbols drift over time (delistings,
// renames, index changes); per-ticker fetch failures are skipped by the scanner.

// UK — FTSE All-Share investable core (FTSE 100 + FTSE 250 constituents, .L suffix).
export const UK_TICKERS = [
  // FTSE 100
  'AAL.L', 'ABF.L', 'ADM.L', 'AHT.L', 'ANTO.L', 'AUTO.L', 'AV.L', 'AZN.L',
  'BA.L', 'BAB.L', 'BARC.L', 'BATS.L', 'BDEV.L', 'BEZ.L', 'BKG.L', 'BLND.L',
  'BNZL.L', 'BP.L', 'BRBY.L', 'BT-A.L', 'BTRW.L', 'CCH.L', 'CNA.L', 'CPG.L',
  'CTEC.L', 'DCC.L', 'DGE.L', 'DPLM.L', 'EDV.L', 'ENT.L', 'EXPN.L', 'EZJ.L',
  'FCIT.L', 'FRAS.L', 'FRES.L', 'GAW.L', 'GLEN.L', 'GSK.L', 'HIK.L', 'HLMA.L',
  'HLN.L', 'HSBA.L', 'HWDN.L', 'IAG.L', 'ICG.L', 'IHG.L', 'III.L', 'IMB.L',
  'IMI.L', 'INF.L', 'ITRK.L', 'JD.L', 'KGF.L', 'LAND.L', 'LGEN.L', 'LLOY.L',
  'LMP.L', 'LSEG.L', 'MKS.L', 'MNDI.L', 'MNG.L', 'MRO.L', 'NG.L', 'NWG.L',
  'NXT.L', 'PHNX.L', 'PRU.L', 'PSH.L', 'PSN.L', 'PSON.L', 'REL.L', 'RIO.L',
  'RKT.L', 'RMV.L', 'RR.L', 'RS1.L', 'RTO.L', 'SBRY.L', 'SDR.L', 'SGE.L',
  'SGRO.L', 'SHEL.L', 'SMIN.L', 'SMT.L', 'SN.L', 'SPX.L', 'SSE.L', 'STAN.L',
  'STJ.L', 'SVT.L', 'TSCO.L', 'TW.L', 'ULVR.L', 'UTG.L', 'UU.L', 'VOD.L',
  'VTY.L', 'WEIR.L', 'WPP.L', 'WTB.L',
  // FTSE 250 (operating companies; most investment trusts excluded)
  'AAF.L', 'ABDN.L', 'AGR.L', 'AJB.L', 'AML.L', 'APAX.L', 'ASHM.L', 'ATG.L',
  'AVON.L', 'BAKK.L', 'BBY.L', 'BGEO.L', 'BME.L', 'BOY.L', 'BVIC.L', 'BWY.L',
  'BYIT.L', 'CARD.L', 'CBG.L', 'CCC.L', 'CHG.L', 'CKN.L', 'CLIG.L', 'COA.L',
  'CRST.L', 'CURY.L', 'CWK.L', 'DLG.L', 'DLN.L', 'DNLM.L', 'DOM.L', 'DOCS.L',
  'DRX.L', 'EMG.L', 'ENOG.L', 'ESNT.L', 'FDM.L', 'FGP.L', 'FOUR.L', 'FSG.L',
  'FUTR.L', 'GEN.L', 'GFTU.L', 'GNS.L', 'GRG.L', 'GYM.L', 'HAS.L', 'HBR.L',
  'HFD.L', 'HICL.L', 'HILS.L', 'HOC.L', 'HSX.L', 'HTWS.L', 'IBST.L', 'IDS.L',
  'IGG.L', 'INCH.L', 'INDV.L', 'INVP.L', 'IPO.L', 'ITV.L', 'IWG.L', 'JET2.L',
  'JDW.L', 'JMAT.L', 'JUP.L', 'KIE.L', 'KNOS.L', 'LRE.L', 'MAB.L', 'MCG.L',
  'MGAM.L', 'MGNS.L', 'MONY.L', 'MSLH.L', 'MTO.L', 'NCC.L', 'OCDO.L', 'OSB.L',
  'OTB.L', 'OXIG.L', 'PAG.L', 'PAGE.L', 'PETS.L', 'PLUS.L', 'PNN.L', 'POLR.L',
  'PPH.L', 'PZC.L', 'QQ.L', 'RAT.L', 'RDW.L', 'ROR.L', 'RSW.L', 'RWA.L',
  'SAFE.L', 'SCT.L', 'SFOR.L', 'SHB.L', 'SIG.L', 'SRP.L', 'SSPG.L', 'SXS.L',
  'TATE.L', 'TBCG.L', 'TEP.L', 'TLW.L', 'TPK.L', 'TRN.L', 'VCT.L', 'VSVS.L',
  'WG.L', 'WIZZ.L', 'WOSG.L', 'ZIG.L',
];

// USA — S&P 500 + Nasdaq-100 core + high-ADR momentum extras (crypto, quantum,
// space, AI infra — required by the hot-sector scanners; large caps rarely have ADR > 5%).
export const USA_TICKERS = [
  // Mega/large cap core (S&P 500 / Nasdaq-100)
  'AAPL', 'MSFT', 'NVDA', 'GOOGL', 'AMZN', 'META', 'TSLA', 'AVGO', 'BRK-B',
  'LLY', 'JPM', 'V', 'XOM', 'UNH', 'MA', 'ORCL', 'COST', 'HD', 'PG', 'NFLX',
  'JNJ', 'BAC', 'CRM', 'ABBV', 'CVX', 'KO', 'AMD', 'PEP', 'TMO', 'WMT',
  'ADBE', 'MRK', 'CSCO', 'ACN', 'LIN', 'MCD', 'ABT', 'PM', 'INTU', 'GE',
  'IBM', 'TXN', 'QCOM', 'DHR', 'ISRG', 'CAT', 'VZ', 'DIS', 'NOW', 'AMGN',
  'PFE', 'SPGI', 'CMCSA', 'UBER', 'RTX', 'GS', 'NEE', 'UNP', 'AXP', 'T',
  'LOW', 'HON', 'BKNG', 'MS', 'ELV', 'SYK', 'PGR', 'ETN', 'LMT', 'BLK',
  'TJX', 'COP', 'C', 'VRTX', 'PANW', 'ADP', 'MDT', 'ADI', 'MU', 'SBUX',
  'CB', 'BMY', 'FI', 'GILD', 'BSX', 'MMC', 'LRCX', 'PLD', 'AMT', 'DE',
  'SO', 'ANET', 'KLAC', 'MO', 'SCHW', 'UPS', 'DUK', 'ICE', 'AMAT', 'SHW',
  'TT', 'INTC', 'APH', 'CDNS', 'SNPS', 'PYPL', 'CMG', 'WM', 'AON', 'CI',
  'ZTS', 'MSI', 'CL', 'ITW', 'EQIX', 'PH', 'TDG', 'GD', 'NOC', 'CME',
  'MCK', 'FCX', 'TGT', 'EMR', 'USB', 'PNC', 'APD', 'CSX', 'ORLY', 'BDX',
  'WELL', 'MMM', 'AJG', 'ECL', 'CARR', 'MAR', 'ROP', 'HCA', 'TFC', 'NSC',
  'FDX', 'CTAS', 'SLB', 'NXPI', 'AZO', 'PCAR', 'AFL', 'DLR', 'GM', 'F',
  'REGN', 'MRNA', 'EW', 'OKE', 'PSX', 'MPC', 'VLO', 'SPG', 'O', 'SRE',
  'AEP', 'D', 'EXC', 'XEL', 'ED', 'PEG', 'WEC', 'ES', 'AWK', 'CEG',
  'VST', 'NRG', 'GEV', 'KMI', 'WMB', 'HAL', 'BKR', 'DVN', 'FANG', 'EOG',
  'HES', 'OXY', 'CTRA', 'EQT', 'APA', 'MRO', 'TRGP', 'LNG', 'AA', 'NUE',
  'STLD', 'CLF', 'X', 'DOW', 'DD', 'LYB', 'PPG', 'ALB', 'MOS', 'CF',
  'NEM', 'GOLD', 'AEM', 'KGC', 'RGLD', 'WPM', 'FNV', 'PAAS', 'HL', 'CDE',
  'GDX', 'URA', 'CCJ', 'UEC', 'DNN', 'NXE', 'LEU', 'UUUU', 'SMR', 'OKLO',
  'BWXT', 'VRT', 'NVT', 'HUBB', 'PWR', 'FIX', 'EME', 'STRL', 'IESC', 'DY',
  'MTZ', 'ACM', 'J', 'KBR', 'FLR', 'GVA', 'ROAD', 'PRIM', 'AGX', 'BLDR',
  'MHO', 'PHM', 'DHI', 'LEN', 'NVR', 'TOL', 'KBH', 'TMHC', 'GRBK', 'SKY',
  'DECK', 'NKE', 'LULU', 'ONON', 'CROX', 'SKX', 'RL', 'TPR', 'GPS', 'ANF',
  'URBN', 'AEO', 'BURL', 'ROST', 'FIVE', 'OLLI', 'DG', 'DLTR', 'BBY', 'ULTA',
  'ELF', 'EL', 'CELH', 'MNST', 'KDP', 'STZ', 'TAP', 'BUD', 'SAM', 'K',
  'GIS', 'HSY', 'MDLZ', 'KHC', 'CPB', 'CAG', 'SJM', 'HRL', 'TSN', 'KR',
  'SYY', 'DPZ', 'YUM', 'QSR', 'WEN', 'SHAK', 'CAVA', 'WING', 'TXRH', 'DRI',
  'EAT', 'CAKE', 'BROS', 'DASH', 'ABNB', 'EXPE', 'RCL', 'CCL', 'NCLH', 'VIK',
  'MTN', 'LVS', 'WYNN', 'MGM', 'CZR', 'DKNG', 'FLUT', 'PENN', 'CHDN', 'GENI',
  'AAL', 'DAL', 'UAL', 'LUV', 'ALK', 'JBLU', 'SAVE', 'BA', 'HEI', 'TXT',
  'LHX', 'HWM', 'AXON', 'KTOS', 'AVAV', 'LDOS', 'CW', 'MOG-A', 'DRS', 'PL',
  'RKLB', 'ASTS', 'LUNR', 'RDW', 'ACHR', 'JOBY', 'BLDE', 'SPCE', 'MNTS', 'SIDU',
  'PLTR', 'APP', 'SNOW', 'CRWD', 'ZS', 'NET', 'DDOG', 'MDB', 'TEAM', 'WDAY',
  'HUBS', 'TWLO', 'OKTA', 'S', 'CYBR', 'FTNT', 'CHKP', 'TENB', 'RPD', 'QLYS',
  'GTLB', 'PATH', 'AI', 'BBAI', 'SOUN', 'PLAB', 'ARM', 'TSM', 'ASML', 'SMCI',
  'DELL', 'HPE', 'HPQ', 'WDC', 'STX', 'PSTG', 'NTAP', 'ON', 'MCHP', 'MRVL',
  'SWKS', 'QRVO', 'MPWR', 'TER', 'ENTG', 'AMKR', 'COHR', 'LITE', 'AAOI', 'CIEN',
  'ANSS', 'CRUS', 'SLAB', 'RMBS', 'ALGM', 'WOLF', 'LSCC', 'POWI', 'CRDO', 'ALAB',
  'NBIS', 'CRWV', 'IREN', 'CIFR', 'MARA', 'RIOT', 'CLSK', 'HUT', 'WULF', 'CORZ',
  'BTBT', 'BITF', 'HIVE', 'COIN', 'HOOD', 'MSTR', 'GLXY', 'CRCL', 'SQ', 'AFRM',
  'UPST', 'SOFI', 'LC', 'TOST', 'BILL', 'PAYC', 'PCTY', 'FOUR', 'GPN', 'FIS',
  'NU', 'MELI', 'SE', 'SHOP', 'ETSY', 'EBAY', 'CHWY', 'W', 'CVNA', 'CARG',
  'RDDT', 'PINS', 'SNAP', 'SPOT', 'ROKU', 'TTD', 'APPS', 'MGNI', 'PUBM', 'ZETA',
  'DUOL', 'COUR', 'UDMY', 'CHGG', 'RBLX', 'U', 'TTWO', 'EA', 'MTCH', 'BMBL',
  'HIMS', 'OSCR', 'TDOC', 'DOCS', 'GDRX', 'TMDX', 'PODD', 'DXCM', 'ALGN', 'IDXX',
  'ILMN', 'PACB', 'TXG', 'NTRA', 'GH', 'EXAS', 'TEM', 'RXRX', 'SDGR', 'ABCL',
  'CRSP', 'NTLA', 'BEAM', 'EDIT', 'VERV', 'ALNY', 'SRPT', 'RARE', 'BMRN', 'INCY',
  'EXEL', 'HALO', 'INSM', 'ARWR', 'IONS', 'AXSM', 'ACAD', 'SAGE', 'PTCT', 'FOLD',
  'VKTX', 'TGTX', 'CPRX', 'HROW', 'LQDA', 'ARDX', 'CORT', 'KRYS', 'RVMD', 'CYTK',
  'IONQ', 'RGTI', 'QBTS', 'QUBT', 'QMCO', 'ARQQ', 'LAES',
  'GRAB', 'BIDU', 'BABA', 'JD', 'PDD', 'NTES', 'TME', 'BILI', 'IQ', 'FUTU',
  'TIGR', 'NIO', 'XPEV', 'LI', 'ZK', 'RIVN', 'LCID', 'PSNY', 'CHPT', 'EVGO',
  'BLNK', 'QS', 'ENVX', 'AMPX', 'FLNC', 'ENPH', 'SEDG', 'RUN', 'ARRY', 'SHLS',
  'FSLR', 'NXT', 'CSIQ', 'JKS', 'DQ', 'PLUG', 'BE', 'BLDP', 'FCEL', 'GEVO',
  'LAC', 'SGML', 'PLL', 'MP', 'TMC', 'VALE', 'RIG', 'TDW', 'WFRD', 'NOV',
  'CHX', 'LBRT', 'PTEN', 'HP', 'NBR', 'AROC', 'KOS', 'CRK', 'AR', 'RRC',
  'SWN', 'BTU', 'ARCH', 'AMR', 'HCC', 'CEIX', 'WHD', 'VTLE', 'SM', 'MGY',
  'GKOS', 'ZBRA', 'TRMB', 'GRMN', 'GPRO', 'SONO', 'IRBT', 'PTON', 'LYFT', 'BIRD',
];
